# Use an official Node.js runtime as a parent image
FROM node:14-alpine

# Set the working directory to /app
WORKDIR /app

# Install the create-react-app CLI tool
RUN npm install -g create-react-app

# Generate a new React application
RUN create-react-app my-app

# Change the working directory to the new application
WORKDIR /app/my-app

# Edit the App.js file to display a custom message
RUN sed -i 's/Add any content for your website/let your light shine!/g' /app/my-app/src/App.js


# Expose port 3000 to the Docker host
EXPOSE 3000

# Start the application using the built-in development server
CMD ["npm", "start"]

